// <auto-generated />
namespace Rabbit.IWasThere.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixCountAllMessagesSP2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixCountAllMessagesSP2));
        
        string IMigrationMetadata.Id
        {
            get { return "201509100902190_FixCountAllMessagesSP2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
